{{- if and .Values.ingress.enabled .Values.monitoring.enabled -}}
{{- if or .Values.monitoring.prometheus.enabled .Values.monitoring.grafana.enabled -}}
{{- $fullName := include "civicshield.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-monitoring
  labels:
    {{- include "civicshield.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.monitoring.prometheus.enabled }}
    - host: prometheus.{{ .Values.ingress.hosts.0.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-prometheus
                port:
                  number: {{ .Values.monitoring.prometheus.service.port }}
    {{- end }}
    {{- if .Values.monitoring.grafana.enabled }}
    - host: grafana.{{ .Values.ingress.hosts.0.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-grafana
                port:
                  number: {{ .Values.monitoring.grafana.service.port }}
    {{- end }}
{{- end }}
{{- end }}