{{- if .Values.monitoring.enabled -}}
{{- if .Values.monitoring.prometheus.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "civicshield.fullname" . }}-prometheus
  labels:
    {{- include "civicshield.labels" . | nindent 4 }}
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "civicshield.selectorLabels" . | nindent 6 }}
      app: prometheus
  template:
    metadata:
      labels:
        {{- include "civicshield.selectorLabels" . | nindent 8 }}
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: "{{ .Values.monitoring.prometheus.image.repository }}:{{ .Values.monitoring.prometheus.image.tag }}"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        - name: prometheus-storage
          mountPath: /prometheus
        resources:
          {{- toYaml .Values.monitoring.prometheus.resources | nindent 10 }}
      volumes:
      - name: prometheus-config
        configMap:
          name: {{ include "civicshield.fullname" . }}-prometheus-config
      - name: prometheus-storage
        emptyDir: {}
{{- end }}

{{- if .Values.monitoring.grafana.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "civicshield.fullname" . }}-grafana
  labels:
    {{- include "civicshield.labels" . | nindent 4 }}
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "civicshield.selectorLabels" . | nindent 6 }}
      app: grafana
  template:
    metadata:
      labels:
        {{- include "civicshield.selectorLabels" . | nindent 8 }}
        app: grafana
    spec:
      containers:
      - name: grafana
        image: "{{ .Values.monitoring.grafana.image.repository }}:{{ .Values.monitoring.grafana.image.tag }}"
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: {{ .Values.monitoring.grafana.adminPassword | quote }}
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        resources:
          {{- toYaml .Values.monitoring.grafana.resources | nindent 10 }}
      volumes:
      - name: grafana-storage
        emptyDir: {}
{{- end }}
{{- end }}