{{- if .Values.database.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "civicshield.fullname" . }}-redis
  labels:
    {{- include "civicshield.labels" . | nindent 4 }}
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    {{- include "civicshield.selectorLabels" . | nindent 4 }}
    app: redis
{{- end }}