apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backups-pvc
  namespace: civicshield
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp2