apiVersion: apps/v1
kind: Deployment
metadata:
  name: civicshield-prometheus
  namespace: civicshield
  labels:
    app: civicshield
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: civicshield
      component: monitoring
  template:
    metadata:
      labels:
        app: civicshield
        component: monitoring
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.37.0
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        - name: prometheus-storage
          mountPath: /prometheus
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: prometheus-storage
        persistentVolumeClaim:
          claimName: civicshield-prometheus-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: civicshield-grafana
  namespace: civicshield
  labels:
    app: civicshield
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: civicshield
      component: monitoring
  template:
    metadata:
      labels:
        app: civicshield
        component: monitoring
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:8.1.0
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: civicshield-secrets
              key: grafana-password
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
          requests:
            memory: "256Mi"
            cpu: "125m"
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: civicshield-grafana-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: civicshield-prometheus
  namespace: civicshield
  labels:
    app: civicshield
    component: monitoring
spec:
  selector:
    app: civicshield
    component: monitoring
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9090
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: civicshield-grafana
  namespace: civicshield
  labels:
    app: civicshield
    component: monitoring
spec:
  selector:
    app: civicshield
    component: monitoring
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: civicshield
  labels:
    app: civicshield
    component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'civicshield-backend'
      static_configs:
      - targets: ['civicshield-backend:8000']
    - job_name: 'civicshield-frontend'
      static_configs:
      - targets: ['civicshield-frontend:3000']
    - job_name: 'civicshield-ai'
      static_configs:
      - targets: ['civicshield-ai:5000']
    - job_name: 'civicshield-database'
      static_configs:
      - targets: ['civicshield-database:5432']
    - job_name: 'civicshield-redis'
      static_configs:
      - targets: ['civicshield-redis:6379']
    - job_name: 'civicshield-elasticsearch'
      static_configs:
      - targets: ['civicshield-elasticsearch:9200']