apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: civicshield-postgres-pvc
  namespace: civicshield
  labels:
    app: civicshield
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: civicshield-redis-pvc
  namespace: civicshield
  labels:
    app: civicshield
    component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: civicshield-elasticsearch-pvc
  namespace: civicshield
  labels:
    app: civicshield
    component: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: civicshield-grafana-pvc
  namespace: civicshield
  labels:
    app: civicshield
    component: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: civicshield-prometheus-pvc
  namespace: civicshield
  labels:
    app: civicshield
    component: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: civicshield-backups-pvc
  namespace: civicshield
  labels:
    app: civicshield
    component: backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: standard