---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
type: Opaque
data:
  # These values should be base64 encoded
  # echo -n "your-admin-password" | base64
  admin-password: eW91ci1hZG1pbi1wYXNzd29yZA==
  
  # Grafana configuration
  grafana-admin-user: YWRtaW4=